# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    name: Check CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: "d2416/addressesbook"
          ref: "main"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: list git remotes
        run: git remote

      - name: list git remotes url
        run: git remote get-url origin

      # - name: Build with Maven
      #   run: mvn -B package --file pom.xml

      - name: Add Heroku remote
        run: heroku git:remote --app ${{ secrets.HEROKU_BOOK_APP_NAME }}
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_BOOK_APP_NAME }}

      - name: list git remotes
        run: git remote

      - name: list git remotes
        run: git remote rename origin heroku

      - name: list git remotes
        run: git remote

      - name: Push to Heroku
        run: git push heroku main
